# -*- coding: utf-8 -*-
prompt_school_ruler = """Cinematic progressive line-reveal animation on a solid pure bright white background (#FFFFFF), edge to edge. The very first frame is an entirely empty pure white field. High-key lighting. The main illustration is centered and occupies the central three-quarters of the frame, with equal narrow breathing margins on the left and right. The visual weight is divided evenly across the left and right halves, with a small subject anchor in each outer third. The horizon and camera axis are perfectly level: no Dutch angle, no tilted angle, no composition leaning to either side. Static locked-off camera, one continuous 8-second take. The only visible subjects throughout the sequence are a slim wooden measuring ruler at the optical center, a delicate glass hourglass balancing the left, one thin level desktop baseline extending across both outer thirds, and a geometric brass paperweight balancing the right. 0-4s: ultra-fine pale warm-grey graphite linework appears progressively from the empty white field. Every outline is very thin, soft and light, never black or dark charcoal; there are no bold contours, heavy edge lines or dense hatch marks. Begin with one perfectly level minimal baseline. Draw the straight wooden ruler and subtle metric tick notches next, keeping the combined silhouette horizontal rather than diagonal. Extend a single thin baseline equally toward the left and right outer thirds. Add a slender hourglass at left and a small faceted paperweight at right. There is no visible letters, numbers, labels, classroom wall, heavy furniture or person anywhere. Keep all outline contours sparse, pale and softly broken, never darker than 15% grey and never filled as solid outlined blobs. Every detail becomes visible sequentially, never all at once. Previously revealed lines remain delicate and completely stable. 4-8s: an extremely pale, water-heavy watercolor wash develops gently. All color remains low-saturation and transparent, with white showing through every wash. No area becomes dark, dense or fully filled. Use distinct, believable colors for different materials. Restraint means low saturation, not fewer colors or shared hues. The restrained palette is a warm sunny birch-yellow on the wooden ruler, sheer watery azure on the sand inside the hourglass, and faint champagne-gold on the brass paperweight. A tiny trickle of pale blue sand drifts smoothly through the hourglass neck; all ruler and baseline lines remain crisp and still. All other elements remain still. The final composition remains centered, readable and surrounded by generous untouched white space. Style: master-level fine-line illustration with exceptionally thin, pale warm-grey graphite strokes and sophisticated control, maximum line value 25% grey, luminous transparent watercolor, restrained tonal contrast, sophisticated contemporary editorial illustration for thoughtful young learners, generous untouched white space."""

clean_prompt = " ".join(prompt_school_ruler.split())

with open("_작업/prompt_school_ruler.txt", "w", encoding="utf-8") as f:
    f.write(clean_prompt)

import subprocess
res = subprocess.run(["python3", "_작업/verify_prompt.py", "_작업/prompt_school_ruler.txt"], capture_output=True, text=True)
print(res.stdout)

